connectionConfig:
  replicaSet:
    - id: "server1"
      endpoint: "http://127.0.0.1:6001"
  rootCAs: "./crypto/CA/CA.pem"
  logLevel: "info"

sessionConfig:
  userConfig:
    userID: "admin"
    certPath: "./crypto/admin/admin.pem"
    privateKeyPath: "./crypto/admin/admin.key"
  txTimeout: 10s
  queryTimeout: 2s

workloadConfig:
  numOfClients: 2
  loadPerClient: 100
  runtime: 10s
